allowBuilds:
  '@reown/appkit': true
  esbuild: true
  keccak: true
  sharp: true
  unrs-resolver: true
  workerd: true
# Supply chain security configuration. See https://pnpm.io/supply-chain-security for more information.
minimumReleaseAge: 10080 # 7 days
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days
