import Providers from '../Providers/Providers';
import GlobalStyles from './GlobalStyles/GobalStyles';

import App from './App';
import { fontString } from './Fonts';
import Banner from '@/sites/tari-dot-com/ui/Banner/Banner';
import Header from '@/sites/tari-dot-com/ui/Header/Header';
import Footer from '@/sites/tari-dot-com/ui/Footer/Footer';
import GradientBackground from '@/sites/tari-dot-com/ui/GradientBackground/GradientBackground';
import { GoogleAnalytics } from '@next/third-parties/google';
import Script from 'next/script';
import Head from 'next/head';

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <Providers>
            <GlobalStyles />
            <html lang="en" className={fontString}>
                <Head>
                    <link
                        rel="preload"
                        href="https://customer-o6ocjyfui1ltpm5h.cloudflarestream.com/3ed05f3d4fbfd3eec7c4bb911915d1c2/manifest/video.m3u8"
                        as="fetch"
                        type="application/vnd.apple.mpegurl"
                        crossOrigin="anonymous"
                    />
                    <link
                        rel="preload"
                        href="https://customer-o6ocjyfui1ltpm5h.cloudflarestream.com/852dac0dc91d50d399a7349dcc7316a1/manifest/video.m3u8"
                        as="fetch"
                        type="application/vnd.apple.mpegurl"
                        crossOrigin="anonymous"
                    />
                    <link
                        rel="preload"
                        href="https://customer-o6ocjyfui1ltpm5h.cloudflarestream.com/d47e48d7d48b9a0a6835af9546075d88/manifest/video.m3u8"
                        as="fetch"
                        type="application/vnd.apple.mpegurl"
                        crossOrigin="anonymous"
                    />
                </Head>
                <body>
                    <App>
                        <Banner />
                        <Header />
                        {children}
                        <Footer />
                        <GradientBackground />
                    </App>
                    <GoogleAnalytics gaId={`G-K7EWCBLYHN`} />
                    <Script
                        src="https://widget.kapa.ai/kapa-widget.bundle.js"
                        data-website-id="42b8765f-d05f-44b3-9136-8ee736194767"
                        data-project-name="Tari"
                        data-project-color="#9330ff"
                        data-project-logo="/assets/img/node-icon-alt.svg"
                        data-modal-title="Tari's little AI helper"
                        data-modal-disclaimer="Answers have been generated by artificial intelligence and may not be entirely error-free or up-to-date. We recommend independently verifying the content and consulting with professionals for specific advice or information. We do not assume any responsibility or liability for the use or interpretation of this content."
                        data-search-mode-enabled="true"
                        strategy="afterInteractive"
                    />
                </body>
            </html>
        </Providers>
    );
}
